### ISSUE TITLE
https://modulus.io/

### ISSUE THREAD

**Issue by TumnusB** [BTMorton/dice_roller#1]
![error](https://cloud.githubusercontent.com/assets/3604705/19002051/25dd0abe-8742-11e6-8c0a-1853dcfdc5d0.PNG)

**Comment by BTMorton** [comment]
Can you get the "additional logging output above"? It looks like pegjs isn't installing correctly, which is causing it not to build.

**Comment by TumnusB** [comment]
[error.txt](https://github.com/BTMorton/dice_roller/files/503595/error.txt)
just for reference

**Comment by BTMorton** [comment]
This is due to you using the `--production` flag during `npm install`. pegjs is listed as a dev dependency which I'm not going to change, as if this ever gets published, it won't be necessary to download pegjs as well. I'll add `|| exit 0` to the `postinstall` task which should prevent npm from dying if it can't run it.
